spring:
  application:
    name: aiaq
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    async:
      request-timeout: 120000
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/aiaq
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 192.168.21.128
    port: 6379
    timeout: 120000
    password: Zhuang.200296
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /aiaq
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
      timeout: 120s
  tomcat:
    connection-timeout: 120000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.aiaq.controller
aiaq:
  jwt:
    issuer: aiaq # 签发者
    secret: zz # 签名密钥
    expire: 2592000000 # jwt的有效期，默认30天
